// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var SquareVerifier = artifacts.require('./../../zokrates/code/square/verifier.sol');
var proof = require('./../../zokrates/code/square/proof.json');


contract('TestERC721Mintable', async() => {

    // Test verification with correct proof
    // - use the contents from proof.json generated from zokrates steps

        
    // Test verification with incorrect proof

}