// define a variable to import the <Verifier> or <renamedVerifier> solidity contract generated by Zokrates
var SquareVerifier = artifacts.require("Verifier");
var SolnSquareVerifier = artifacts.require("SolnSquareVerifier");
//var SampleProof = require('../../zokrates/code/square/proof1_1');
//var FalseSample = require('../../zokrates/code/square/notproof3_5');

contract('TestSolnSquareVerifier', async(accounts) => {
  before('setup test environment', async function () { 
    this.verifier = await SquareVerifier.new(accounts);         
    this.solnSV = await SolnSquareVerifier.new(this.verifier.address);         
  })

  describe('match soln square verifier spec', function () {
    // Test if a new solution can be added for contract - SolnSquareVerifier
    it('should add a new solution for contract SolnSquareVerifier', async function () { 
        await this.solnSV.addSolution(123, accounts[0]);
    })

    // Test if an ERC721 token can be minted for contract - SolnSquareVerifier
    it('should mint new token by ERC721', async function () { 
    })
  })
})
